### ISSUE TITLE
Possible Double Free Issue in Mir May Compromise Exception Safety in This Crate

### ISSUE THREAD

**Issue by kuzeyardabulut** [splitgraph/seafowl-udf-rust#1]
Hi,
I detect several potential double free bugs were detected in your crate via static analysis.

We shouldn't use code pieces between `Vec::from_raw_parts` and `mem::forget`. Because when these codes unwind, the Vec generated will drop as well as the entity which ptr pointed to. This code block can fix it by using `mem::ManuallyDrop` instead of `mem::forget`.
https://github.com/splitgraph/seafowl-udf-rust/blob/7e54e0c118e46e5404d8f3e306555f9081f2ec99/src/udf.rs#L43-L70

**Comment by mildbyte** [comment]
Thanks for the analysis. This code is intended to run inside of a WASM runtime and so the usual rules don't apply here, in particular the runtime will deallocate the entire linear memory region when the UDF finishes.
